name: Manual Deploy

on:
  push:
    tags:
      - local/*
      - dev/*
  workflow_dispatch:
    inputs:
      environment:
        type: environment
      message:
        required: true
        default: "Write some messsage here"
      dryrun:
        type: boolean
        description: Is dryrun?
        default: true

jobs:
  parse-environment:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.parse-env.outputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github/actions/parse-environment

      - name: Parse environment
        id: parse-env
        uses: ./.github/actions/parse-environment
        with:
          ref: ${{ github.ref }}
          event_name: ${{ github.event_name }}
          environment_input: ${{ github.event.inputs.environment }}

  manual-approval:
    permissions:
      issues: write
    uses: konnta0/ci-cd-sandbox/.github/workflows/manual-approval.yml@main
    needs: parse-environment
    with:
      environment: ${{ needs.parse-environment.outputs.environment }}
      issue-title: "Manual approval"
      issue-body: "Manual approval"
      approvers: "konnta0"
      minimum-approvals: "1"
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: [parse-environment, manual-approval]
    runs-on: ubuntu-latest
    environment: ${{ needs.parse-environment.outputs.environment }}

    steps:
      - name: Show inputs
        run: |
          echo "environment: ${{ needs.parse-environment.outputs.environment }}"
          echo "message: ${{ github.event.inputs.message }}"
          echo "dryrun: ${{ github.event.inputs.dryrun }}"
      - name: Deploy (use environemt secrets)
        run: |
          echo "ENV_SERVER: ${{ secrets.ENV_SERVER }}"
          echo "VAR_FUGA: ${{ vars.VAR_FUGA }}"
      - name: test secrets
        run: |
          echo ENV_SERVER "${{secrets.ENV_SERVER }}" | sed 's/./& /g'
          echo VAR_FUGA "${{ vars.VAR_FUGA }}" | sed 's/./& /g'
