name: Manual Deploy

on:
  push:
    tags:
      - local/*
      - dev/*
  workflow_dispatch:
    inputs:
      environment:
        type: environment
      message:
        required: true
        default: "Write some messsage here"
      dryrun:
        type: boolean
        description: Is dryrun?
        default: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Show inputs
        run: |
          echo "message: ${{ github.event.inputs.message }}"
          echo "dryrun: ${{ github.event.inputs.dryrun }}"
      - name: Deploy (use environemt secrets)
        run: |
          echo "ENV_SERVER: ${{ secrets.ENV_SERVER }}"
          echo "VAR_FUGA: ${{ vars.VAR_FUGA }}"
      - name: test secrets
        run: |
          echo ENV_SERVER "${{secrets.ENV_SERVER }}" | sed 's/./& /g'
          echo VAR_FUGA ${{ vars.VAR_FUGA }}" | sed 's/./& /g'
