name: use docker compose

on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        description: Deploy target
        options:
          - dev1
          - dev2
          - prod

jobs:
  deploy:
    runs-on: first
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Show inputs
        run: |
          echo "target: ${{ github.event.inputs.target }}"
          echo "message: ${{ github.event.inputs.message }}"
          echo "dryrun: ${{ github.event.inputs.dryrun }}"
      - name: Deploy (use environemt secrets)
        run: |
          echo "Deploy target server: ${{ secrets.ENV_SERVER }}"
      - name: checkout
        uses: actions/checkout@v2

      - name: compose up
        run: |
          sleep 10
          docker-compose up -d
